language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.2
    - platform-tools
    - android-22
    - sys-img-armeabi-v7a-android-22
    - addon-google_apis-google-22
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-bcbbd656
    - android-sdk-license-5be876d5
    - android-sdk-license-598b93a6
    - 'android-*'
    - '.*intel.+'

before_install:
  - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"
  - cp xmltemplates/api_keys.xml.template app/src/main/res/values/api_keys.xml
  - mkdir -p app/src/main/res/xml
  - cp xmltemplates/app_tracker.xml.template app/src/main/res/xml/app_tracker.xml
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82

before_script:
  - ./ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &
  - sleep 25 && adb shell input keyevent 82 &

script: ./gradlew connectedCheck
